---
name: 'Setup Nimble environment'
description: 'Setup a Nimble environment and add it to the PATH'
author: 'jmgomez'

inputs:
  nimble-version:
    description: >-
      The Nimble version to download.
      Examples: '0.16.3', 'latest'
    default: 'latest'
    required: false
  nimble-install-directory:
    description: >-
      The Nimble installation directory.
    default: '.nimble_runtime'
    required: false
  parent-nimble-install-directory:
    description: >-
      The Nimble installation parent directory.
      It will be placed in the current directory if this parameter is empty.
    default: ''
    required: false
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: false
  install-dlls:
    description: 'Install Nim DLLs on Windows'
    default: 'true'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Cache Nim DLLs (Windows)
      if: runner.os == 'Windows' && inputs.install-dlls == 'true'
      uses: actions/cache@v4
      id: cache-nim-dlls
      with:
        path: nim-dlls.zip
        key: nim-dlls-${{ runner.os }}

    - name: Download Nim DLLs (Windows)
      if: runner.os == 'Windows' && inputs.install-dlls == 'true' && steps.cache-nim-dlls.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://nim-lang.org/download/dlls.zip -OutFile nim-dlls.zip

    - name: Setup Nim DLLs (Windows)
      if: runner.os == 'Windows' && inputs.install-dlls == 'true'
      shell: pwsh
      run: |
        Expand-Archive -Path nim-dlls.zip -DestinationPath nim-dlls -Force
        echo "$Env:GITHUB_WORKSPACE\nim-dlls" >> $Env:GITHUB_PATH
        echo "SSL_CERT_FILE=$Env:GITHUB_WORKSPACE\nim-dlls\cacert.pem" >> $Env:GITHUB_ENV

    - name: Install nimble
      shell: bash
      run: |
        "${{ github.action_path }}/install_nimble.sh" \
          --nimble-version "${{ inputs.nimble-version }}" \
          --parent-nimble-install-directory "${{ inputs.parent-nimble-install-directory }}" \
          --nimble-install-directory "${{ inputs.nimble-install-directory }}" \
          --os "${{ runner.os }}" \
          --repo-token "${{ inputs.repo-token }}"

    - name: Set PATH for Unix
      shell: bash
      run: |
        parent="${{ inputs.parent-nimble-install-directory }}"
        if [[ "${parent}" = "" ]]; then
          parent="$PWD"
        fi
        echo "$parent/${{ inputs.nimble-install-directory }}/bin" >> "$GITHUB_PATH"
      if: runner.os != 'Windows'

    - name: Set PATH for Windows
      shell: pwsh
      run: |
        $parent = "${{ inputs.parent-nimble-install-directory }}"
        if ($parent -eq "") {
          $parent = "$Pwd"
        }
        echo "$parent\${{ inputs.nimble-install-directory }}\bin" >> $Env:GITHUB_PATH
      if: runner.os == 'Windows'

    - name: Print nimble directory
      shell: bash
      run: |
        echo "installed nimble fullpath: $(which nimble)"

    - name: Print nimble version
      shell: bash
      run: nimble -v
